from .reward import Reward
from .walk_v0 import WalkV0
from .walk_v1 import WalkV1
from .walk_v2 import WalkV2
from .walk_v3 import WalkV3
from .walk_v4 import WalkV4
from .walk_v5 import WalkV5
from .walk_v6 import WalkV6
from .walk_v7 import WalkV7
from .walk_v0Easy import WalkV0Easy
from .walk_v2Easy import WalkV2Easy
from .walk_v4Easy import WalkV4Easy
from .walk_v5Easy import WalkV5Easy
from .hybrid_walk_v0 import HybridWalkV0
from .hybrid_walk_v0_BENCHMARK import HybridWalkBENCHMARK